server:
  port: 8089
spring:
  application:
    name: PAYMENT_SERVICE
  datasource:
    username: postgres
    password: 1106
    url: jdbc:postgresql://localhost:5432/payment_service_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
services:
  product-url: http://PRODUCT_SERVICE/product
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}

    instance:
      preferIpAddress: true


